# Generated by Django 5.0.6 on 2024-06-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id_patient', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('date_born', models.DateTimeField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=80, null=True)),
                ('number_address', models.IntegerField(blank=True, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=100, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('rg', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'patients',
                'managed': True,
            },
        ),
    ]
