# Generated by Django 5.0.6 on 2024-06-21 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedulling',
            fields=[
                ('id_schedulling', models.AutoField(primary_key=True, serialize=False)),
                ('date_hour', models.DateTimeField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('canceled_schedulling', models.BooleanField(default=False)),
                ('obs', models.TextField(blank=True, null=True)),
                ('type_schedulling', models.CharField(blank=True, max_length=100, null=True)),
                ('id_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedulling', to='patient.patient')),
            ],
            options={
                'db_table': 'schedulling',
                'managed': True,
                'unique_together': {('date_hour', 'id_patient')},
            },
        ),
    ]
